In [4]:
import numpy as np

matrix_A = np.array([[1, 2, 3], 
                     [4, 5, 6]])

matrix_B = np.array([[7, 8, 9], 
                     [10, 11, 12]])

result_matrix = matrix_A + matrix_B

print("Matrix A:")
print(matrix_A)

print("\nMatrix B:")
print(matrix_B)

print("\nResultant Matrix (A + B):")
print(result_matrix)


Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8  9]
 [10 11 12]]

Resultant Matrix (A + B):
[[ 8 10 12]
 [14 16 18]]
